blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/thinkmill/emery/discussions/categories/questions
    about: Ask the community for help
  - name: Request a Feature
    url: https://github.com/thinkmill/emery/discussions/categories/ideas
    about: Share ideas for new features
