name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup-deps

      - name: Unit tests
        run: yarn jest --ci --runInBand

  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup-deps

      - name: Prettier
        run: yarn lint:prettier

      - name: ESLint
        run: yarn lint:eslint

      - name: TypeScript
        run: yarn lint:types
